      const data ={
        Products:[
    {
        //_id: '1',
        name: 'JLAWN-S-JDS-22-1048 Iksha (22-1065)',
        slug: 'jlawn-s-jds-22-1048-iksha-22-1065',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/j/d/jds-22-1048_2_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=755&width=589&canvas=589:755',
        price: 2690,
             color: 'BLUE-GREEN',
            fabric: 'Lawn',
            size: '2 piece',
            productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
            volume: 'Volume 3 2022',
            procollection: 'Festive Affair 22',
            design: 'Embroidered Lawn Shirt With Lawn Dupatta',
            disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
            note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       countInStock: 3,
       brand: 'J.',
       category: 'Stitched',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '2',
        name: 'JLAWN-S-JDS-22-1062-IKSHA',
        slug: 'jlawn-s-jds-22-1062-iksha',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/j/d/jds-22-1045_1_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=755&width=589&canvas=589:755',
        price: 2690,
        color: 'BLUE-GREEN',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 3,
       brand: 'J.',
       category: 'Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '3',
        name: 'JLAWN-S-JDS-22-1057 Toucan',
        slug: 'jlawn-s-jds-22-1057-toucan',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/j/d/jds-22-1057_1_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=436',
        price: 2690,
        color: 'Multicolor',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 0,
       brand: 'J.',
       category: 'Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '4',
        name: 'JLAWN-S-JDS-21-1113 Woven',
        slug: 'jlawn-s-jds-21-1113-w0ven',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/j/d/jds-21-1113_1_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=436',
        price: 2690,
        color: 'BLUE-GREEN',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 3,
       brand: 'J.',
       category: 'Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '5',
        name: 'JLAWN-S-21-377 Ajrak',
        slug: 'jlawn-s-jds-21-377-ajrak',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/2/1/21-377-1_1_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=436',
        price: 2690,
        color: 'BLUE-GREEN',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 3,
       brand: 'J.',
       category: 'Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '6',
        name: 'JLAWN-S-21-373 Classic',
        slug: 'jlawn-s-jds-21-373-1048classic',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/2/1/21-373_1_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=436',
        price: 2690,
        color: 'Maroon Red',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 3,
       brand: 'J.',
       category: 'Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '7',
        name: 'JLAWN-S-JDS-21-1110 Octagonals',
        slug: 'jlawn-s-jds-21-1110-octagonals',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/j/d/jds-21-1110_1_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=436',
        price: 2490,
        color: 'BLUE-WHITE',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 3,
       brand: 'J.',
       category: 'Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '8',
        name: 'JLAWN-S-JDS-21-1109 Multy Boxes',
        slug: 'jlawn-s-jds-21-1109-multy-boxes',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/j/d/jds-21-1109_1_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=436',
        price: 2690,
        color: 'MULTI-GREEN',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 3,
       brand: 'J.',
       category: 'Un-Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
    {
        //_id: '9',
        name: 'JLAWN-S-JDS-22-1048 Iksh (22-1065)',
        slug: 'jlawn-s-jds-22-1048-iksha-1065',
        embroidered1: 'Printed Lawn Dupatta: 2.5 Meters',
        embroidered2: 'Embroidered Printed Lawn Shirt: 2 meters',
        addOn: '1.25 Meters Embroidered Border',
        image: 'https://www.junaidjamshed.com/media/catalog/product/j/d/jds-22-1048_2_.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=755&width=589&canvas=589:755',
        price: 2690,
        color: 'BLUE-GREEN',
        fabric: 'Lawn',
        size: '2 piece',
        productCateogry: 'Unstitched 2 Piece - Shirt and Dupatta',
        volume: 'Volume 3 2022',
        procollection: 'Festive Affair 22',
        design: 'Embroidered Lawn Shirt With Lawn Dupatta',
        disclamier: 'Due to the photographic lighting & different screen calibrations, the colors of the original product may slightly vary from the picture',
       countInStock: 3,
       brand: 'J.',
       category: 'Un-Stitched',
       note:'*Note: Actual fabric color, style and composition may differ slightly from the product image.',
       ratings: 4.5,
       numReviews: 310,
    },
]
      }
export default data;